apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-logic
  template:
    metadata:
      labels:
        app: business-logic
    spec:
      containers:
      - name: business-logic
        image: bendonnaloia/email-campaign-service:latest  # Updated to match your Docker Hub image
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "development"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: business-logic
spec:
  selector:
    app: business-logic
  ports:
  - port: 8080
    targetPort: 8080 